fix(setup.cfg): description-file -> description_file
It fixes #97 (install on python 3.12):
```
Building wheels for collected packages: ansible-kernel
  Building wheel for ansible-kernel (pyproject.toml): started
  Building wheel for ansible-kernel (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for ansible-kernel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [156 lines of output]
      /tmp/pip-build-env-p908b0re/overlay/lib/python3.12/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
```